# Generated by Django 2.2.14 on 2020-07-22 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('rating', models.FloatField()),
                ('description', models.CharField(max_length=256)),
                ('reviewer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_reviewer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
